{{- if .Values.crds.install }}
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    {{- if .Values.crds.keep }}
    "helm.sh/resource-policy": keep
    {{- end }}
    {{- with .Values.crds.annotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  labels:
    {{- include "helm-namespaced.labels" . | nindent 4 }}
  name: {{ .Values.crds.name }}
  namespace: {{ .Values.namespace }}
spec:
  group: {{ .Values.crds.group }}
  names:
    kind: Operator
    listKind: OperatorList
    plural: operators
    shortNames:
    - opr
    - oprs
    singular: operator
  scope: Namespaced
  versions:
  - name: v1
    schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                {{- with .Values.crds.properties }}
                {{- toYaml . | nindent 16 }}
                {{- end }}
    served: true
    storage: true
{{- end }}